<?php

$quotes = [
    "When someone fakes a smile, don't get mad, maaannn. At least they're trying.",
    "Fish may swim in schools, but that doesn't mean they're smart, maaannn.",
    "Seagulls make a lot of noise without actually saying anything, maaannn. Do you know a seagull?",
    "Don't kid yourself, maaan. If you eat lobster, you're just eating a big bug.",
    "If you want to adopt a houseplant, maaan, make sure it's housebroken.",
    "Why is a pizza folded over called a calzone? Why isn't it still called a pizza? What's their agenda, maaan?",
    "Heroes aren't necessarily the dudes who run into danger, but the dudes who stop you from doing the same.",
    "Live life like a sponge. You gotta soak it all up.",
    "\"Happy as a clam\" isn't about HOW happy you are. It's about being the KIND of happy that clams are.",
    "\"Square\" isn't a shape—it's a state of mind, maaan.",
    "A belly flop is just a swan dive getting workshopped.",
    "A bonfire is a big fire, right? So is an ocean just a bonlake?",
    "A child's laugh...and a horn section with a sax in front. That's it. That's the orchestra pit of the universe.",
    "A good friend will tell you when you've got food stuck in your teeth. A great friend will get ya some floss.",
    "A guy made dogs drool by ringing a bell, but so what? Bells make EVERYONE drool. Bells are delicious!",
    "A vest is the square root of a jacket. And, like...a hat is just hair squared. There's a lot of math in clothes.",
    "Afterthoughts are still thoughts. They just come after other thoughts.",
    "All things in moderation, including moderation. That's my recipe for chocolate-chip cookies, maaan.",
    "An empty milk carton in the fridge just means someone's not quite ready to accept the truth, maaan.",
    "Ant hills are just cities...but for ants!",
    "Anyone who sleeps on a bed of clams must have serious back issues. Maaan, those things are firm.",
    "Anyone who tells you to get your ducks in a row has never met a duck. Maaan, they do not follow directions.",
    "Are fossils bones that turned to stone, or are bones just rocks in denial about their true nature?",
    "Backstroke, breaststroke, crawl stroke...easy. Luck stroke, genius stroke, and golf stroke...not so much.",
    "Before you blow your Bells on fancy shades, realize you can just squint. Stick it to Big Sunglasses, maaan!",
    "Biting the inside of your mouth while you eat is your body's way of saying, \"Slow down, maaan. Enjoy the food.\"",
    "Blue skies and blueberries are happy things. So why is someone \"blue\" when they're feelin' sad, maaan?",
    "Blueberries are blue and blackberries are black, so how come I can't buy rasp-colored shorts, maaan?",
    "Books are like mouths with a hundred paper tongues. And each one's got important stuff to say.",
    "Candles are just crayons in the color of fire.",
    "Castles are just, like, houses that're wearing armor, maaan.",
    "Cats always land on their feet, but that's just because feet are, like, the bottom part of cats.",
    "Cheese is just milk that's been lucky enough to age gracefully.",
    "Constellations are just a hoax cooked up by Big Space. What do I see when I look up? Pinholes, maaan.",
    "Cookies fresh out of the oven are like warm hugs for your mouth. And your mouth...maaan, it needs hugs too.",
    "Dentists should set up shop at airports. Quick teeth cleaning before a flight? Why not, maaan.",
    "DJs better watch it. If they keep droppin' the bass, they're gonna break it. But we'll all end up payin'.",
    "DNA, maaan. They say it's what we're all made of. But if I'm made of letters...pretty sure it's OTTE and R.",
    "Do lost socks end up in a sock dimension? Maybe that's where they meet their perfect match, maaan...",
    "Do roosters go back to sleep after they wake everyone up? I mean, they're pretty much done for the day.",
    "Do you think ducks get confused during heated dodgeball matches?",
    "Does a missing sock think it's missing? Maybe it just chose the life of adventure, and that's cool.",
    "Don't judge a book by its cover. Judge it by the dedication. \"To Mom\" or nothin', maaan.",
    "Don't let tomatoes confuse you. Are they a fruit, or are they a vegetable? Doesn't matter. Just let it go, maaan.",
    "Downward-facing dog might be a yoga pose, maaan, but upward-facing otter is a way of life.",
    "Dragons are what every lizard aspires to be. Maaan, those lizards must be so disappointed.",
    "Dreams are like the greatest-hits shows of your unconscious—mostly old footage to save money.",
    "Dust is life tucking you in veeeeery slowly. If we could stop tossing and turning, think how cozy we'd be.",
    "Ever been to a scarecrow party? Everyone just sorta hangs around, maaan... Boooooriiiing!",
    "Ever feel like it's a tube-shaped world...and we're just ants crawling around on a roll of paper towels?",
    "Ever mix up your dreams and your memories? Makes you wonder which one is real, maaan.",
    "Ever read a book about gravity? They're impossible to put down, maaan...",
    "Ever tried to put a donut hole back into a donut? Maaan, one size does NOT fit all.",
    "Ever wonder why they call it a flower bed? They always seem real awake to me.",
    "Ever wondered what space looks like when they turn on the lights? I bet it's like some big, empty warehouse.",
    "Every day is the best day of my life, maaan. And I'm not just sayin' that because of the scallops.",
    "Every sunset is just nature dunkin' on us, nice and slow. She's making sure we know she owns the court.",
    "Everyone knows the funny bone isn't funny, maaan. So when are we gonna start calling it the ouchy bone?",
    "Everyone's always trying to get in shape. Circle. Square. Triangle. I say love your own geometry, maaan.",
    "Everyone's heard of an eager beaver. But otters are 100 times more eager. So why don't we get credit for it?",
    "Everything changes. Sometimes it's scary, sometimes it's a relief, and sometimes it means dinner's ready.",
    "Eyeballs are like windows so your brain can look outside, and your brain needs that sunshine, maaan!",
    "Feelin' down? Write a sad poem, and then toss it in a volcano. Then, like, sit back and watch the lava. Whoa...",
    "Feet are like hands you stand on.",
    "Flowers are just gizmos that turn dirt and sunlight into pretty colors.",
    "Folks are always seein' in clouds what they wanna see, but someday they're gonna miss seein' the storm.",
    "Folks kept tellin' me my shirt was on inside out the other day, but, maaan, I was dressin' for me, not for them.",
    "Folks often have their best thoughts in the shower. That's why I spend all my time in the water.",
    "Folks say you can't have too much of a good thing, but after three gallons of ice cream, it stops feeling true.",
    "Friendship isn't a boat you crew alone. You never know when you'll need all hands on deck for a storm.",
    "Getting framed sounds like it oughta be a good thing. Like they're hangin' your photo up in the hall of fame.",
    "Gold is just rocks with good makeup.",
    "Grammar is just word jail, maaan. Words gotta be free. Rules that who wasn't this need, like?",
    "Hard shell, milk on the inside, kinda hairy... Coconuts have a lot going on, maaan.",
    "Have you ever noticed there are rock stars but no roll stars? Whatever happened to rock AND roll, maaan?",
    "Herding cats is hard. But you know what's harder? Herding crocodiles. Maaan, they've got some attitude!",
    "Holes are like mountains made of nothing, maaan.",
    "Hot springs are naturally occurring hot tubs, and they're home to the most relaxed rocks on earth, maaan.",
    "How are there all those thousands of words out there, but nobody's come up with a rhyme for orange, maaan?",
    "How come drawers are where you keep your drawers? Pointlessly confusing, maaan. No need for it.",
    "How come everyone's always askin' where people are from, maaan? What I wanna know is: Where you goin'?",
    "How cool would it be to squeeze a cloud, maaan? You could, like, make a rainstorm as big as your fist.",
    "I had a nightmare once that a scallop was eating me. But when I woke up, I thought about it, and...fair play.",
    "I knew a bull once. He ran a real successful china shop. So, don't generalize, maaan. Just...don't.",
    "I love birthday cake, but why stop there? Some Tuesday cake would hit the spot once or twice a week.",
    "I see a lot of stationary bicycles, but never any stationary unicycles. They must all be at the clown-college gym.",
    "I want a machine that turns toast back into soft bread. I've got too many toast regrets, maaan...",
    "Ice is just water that's lost its spirit of adventure, maaan.",
    "If 13 is an unlucky number, why do they call it a baker's dozen? That's a free donut, maaan!",
    "If birds fly, why don't flies bird? Maybe we'd like 'em more if they did.",
    "If dinosaurs turned into oil, and oil is what makes cars go, why are dinosaurs such bad drivers?",
    "If every star were a candle...we'd have wax, like, ALL OVER the place.",
    "If eyes are windows to the soul, is the mouth a garage door? Makes sense. I always forget to close mine.",
    "If folks make wishes at wishing wells, are they only allowed well-wishing?",
    "If kayak is still kayak backward, how do you know if you're saying it in the right direction? Think about it...",
    "If life doesn't give you lemons, but it does give you potatoes, don't try making potatoade, maaan.",
    "If molecules are made of atoms, and atoms are made of even smaller things...like, how deep does this go?",
    "If she's sellin' seashells by the seashore, is that like some dude sellin' sticks in a forest? Whoa...",
    "If the sun didn't set sometimes, we'd never get to see the other stars.",
    "If the world's your oyster, maaan, pay the shellfish forward. Some hungry otter probably needs a snack.",
    "If time is always running out...are we doing something to chase it away?",
    "If time is relative, then a calendar has gotta be, like, a family tree.",
    "If variety is the spice of life, then friends have gotta be, like, the <random sweet food>.",
    "If you can walk a mile in someone else's shoes, you totally should. Free shoes for a whole mile, maaan!",
    "If you can't get your jam out of the jar, does that mean you're in a jammed-jam jam?",
    "If you don't have enough utensils to attack all the food on your plate, you need reinforkments, maaan.",
    "If you dream of eating carrots, does your eyesight improve? Probably. If you wait until it's light out to check.",
    "If you ever need a shoulder to cry on, I'm your otter. Or, like, you could cry on one of my other limbs, I guess.",
    "If you gotta say something that's hard, be sure it comes from a place of love...or, at least, a place of pizza.",
    "If you love someone, send 'em a mixtape, and then think about it for 15 years. Works every time, maaan.",
    "If you love your job, you'll never work a single day. Unless you're a heavy-metal drummer. That's work.",
    "If you show up at the water balloon fight with a sponge, you're gonna get soaked, man. And that's A-OK!",
    "If you tell a joke in the forest and no one laughs, are you, like, a tree, maaan? Whoa...",
    "If you wanna get ahead in life, you gotta pick a direction first, maaan!",
    "If your philosophy can't be summed up in three words on a T-shirt, maaan, it's just too much work.",
    "If you're cool with wearing your pajamas all day, maybe you actually just like wearing your clothes to bed.",
    "If you're running on all fours, would you ever, like, stub your fingers?",
    "If you're sitting on only half a suggestion, isn't that just a suggestion of a suggestion, maaan?",
    "Isn't your birthday just the anniversary of something somebody else did? Think about it, maaan.",
    "It's always a good deal to buy something half off. You usually still get the full thing anyway, maaan.",
    "It's hard to stay mad if you're eatin' cotton candy. Mostly because you'll be focused on how sticky you are.",
    "It's important to take slow, deep breaths when you get mad. Short, fast ones just make you lightheaded.",
    "It's impossible to mail boomerangs. No matter how many stamps you put on 'em, they always come back.",
    "It's more fun to ride a slow bike fast than a fast bike slow. But, like, a waterslide is more fun than ANY bike.",
    "It's not all about the Bells, maaan. There's also weeding, and fishing, and crafting, and bug catching, and...",
    "It's OK to be a couch potato. Just don't be a bed yam. Maaan, that's just not cool.",
    "It's OK to be scared of stuff you think is scary. Like sharks. Sharks scare me, and that's OK.",
    "It's OK to laugh even when you don't get the joke. It feels good either way, maaan.",
    "It's really easy to forget you have toes...until you stub one. Then it's like, \"What are these things, man?\"",
    "I've always wondered why they call it \"aftermath\"... As far as I know, math is still happening, maaan.",
    "I've got a washer and a dryer, but, maaan, what I really need is a put-away-er.",
    "Laughter is your brain getting so excited, it forgets how lungs work. \"Hur hur!\" It's the best malfunction.",
    "Life is like a pearl... It's hard and shiny and it should smell like the ocean.",
    "Lightning is a game of tag you can play with physics...but physics plays ROUGH.",
    "Lions are the kings of the jungle, but they live in the savanna. So, do they like ruling from a distance, or what?",
    "Live your life one scallop at a time. The rest is just details.",
    "Lots of folks try to take the easy road, but, maaan, that just means you've gotta deal with a lot of traffic.",
    "Lots of folks wish for world peace. Not me. I wish for world pizza. Hard to fight when you're eating pizza.",
    "Maaaaan...I know I say that a lot, but what do I even mean by it? Maaaaan!",
    "Maaan, gravity gets a bad rap. It's just, like, the planet's way of asking us to stick around.",
    "Maaan, if you waste your time doing something you enjoy, then you don't waste your time.",
    "Maaan, sweet dreams are real sweet. But have you ever had a sour dream? Can't recommend it.",
    "Maaan. If night and day could just work out their differences, we'd always live in golden hour.",
    "Magic is just science with your eyes closed, maaan.",
    "Makin' friends is a lot like makin' music. It's a soundtrack for your life, maaan, wrong notes and all.",
    "Maybe a waffle is called a waffle 'cause it can't decide if it wants to be a pancake. You gotta wonder...",
    "Maybe statues are just folks who aren't in such a rush all the time, maaan.",
    "Maybe we should put the cart before the horse sometimes. I bet horses like to mix things up once in a while.",
    "Maybe when we get really dizzy, that's actually us noticing how the world is always rotating.",
    "Mint is weird. Like, how does a flavor make your mouth feel cold? Barely makes sense, but, maaan, it's cool!",
    "Most things are more afraid of you than you are of them. Except for, like, mosquitoes...maaan, run from those.",
    "Music is just air gettin' its dance on, maaan. We're all breathing shy songs that want to cut a rug.",
    "Never count your chickens before they've hatched. You gotta respect their privacy, maaan...",
    "Next time you're feeling down, ask yourself: Am I blue, or do I just need to eat a big pile of scallops?",
    "No one likes a traffic jam. But traffic jelly? Slap some peanut butter on it and it's aaaall good.",
    "Nobody ever asks a tree what its five-year plan is, maaan. Maybe that's why they can grow so tall.",
    "Nobody ever asks the pineapple if it WANTS to be on the pizza, maaan.",
    "NookPhones give you all those apps to keep you from ordering an entree. They're fillin' us up on bread, maaan.",
    "Noses are weird, maaan. They're like tiny vacuums on your face. But where do all the smells even go?",
    "Nothing is impossible. Except for ignoring your paws when they’re sticky. Maaan, try it sometime.",
    "Octopuses have eight arms. You know what that means? Eight. Ice Cream. Cones.",
    "Oh maaan...I forgot what I was gonna say. Or, like, maybe my words just had somewhere else to be.",
    "One otter's trash is another otter's recycling. Blue, green... It's so hard to tell those bins apart, maaan.",
    "Outer space doesn't need to be the way that it is...but it is, maaan. So unreasonable.",
    "Owls make terrible news reporters. I mean, they only ever ask the one question, maaan.",
    "Pancakes, maaan... Just... Pancakes.",
    "Patting your head and rubbing your belly at the same time...you gotta work for it. But, maaan, it is worth it.",
    "Peanut butter knows EXACTLY what it's doing...and it should be ashamed of itself, maaan.",
    "People are always looking at clouds and seeing whatever they want. Just let a cloud be a cloud, maaan.",
    "People ask what's the difference between morals and ethics. Only five out of six letters, maaaan!",
    "People ask, \"Where does the time go?\" But I know, maaan. There's a used-time store near my place.",
    "People compare tuna to chicken, but that's so unfair, maaan. Some of the bravest folks I know are tuna.",
    "People gotta stop asking if a hot dog is a sandwich. Just eat your lunch, maaan.",
    "People used to try to turn lead into gold, but did they ever think about just accepting lead the way it was?",
    "Procrastinating is just havin' optimism for the future while optimizin' the present, maaan.",
    "Remember, even if things are bad, there are always hammocks.",
    "Rock? Ska? Polka? All insecure. You don't have to name the genre in all those song titles. We'll remember.",
    "Rocks are the oysters of the land.",
    "Rule of thumb, maaan. Spend more time <doing random hobby> than you do thinkin' about work.",
    "Sailboats got sails. Powerboats got power. Paddleboats got paddles. So you tell me...what's up with kayaks?",
    "Six is afraid of seven because seven ate nine. But, maaan, it was a setup! The real culprit? Negative seven.",
    "Snakes don't have any limbs...but on the other hand, LIMBS don't have any SNAKES either, maaan.",
    "So brunch is between breakfast and lunch, but what's it called when you eat <random savory food> at 3 AM?",
    "Some folks get offended when you call a spider an insect, but you never hear a spider complain, maaan!",
    "Some folks will tell you not to buy a boat. Bet they'll also tell you not to eat candy or listen to music!",
    "Some ideas are better when they're half-baked, maaan. Just like cookies. Gooey on the inside is where it's at.",
    "Some languages have tons of words for snow, or for sunshine. But which one has the most words for pizza?",
    "Some people are the apple of your eye. Others are just a pie in your face. Apples, maaan. Stick with them.",
    "Some people don't like driftwood, but I can really see where it's coming from, you know?",
    "Sometimes a delivery guy in a pizza hat is so much better than a knight in shining armor, maaan.",
    "Sometimes I dream about throwing the best party anyone's ever seen, maaan. Pascal's Rager, they'd call it.",
    "Sometimes I think about learning to make bread, but then I remember I'm already pretty good at buying it.",
    "Sometimes I wish I was a bird. It's pretty obvious why—so I could turn my head back and forth real fast!",
    "Static electricity is just carpet's way of playing a practical joke on you.",
    "Stop and smell the roses, they say. But do roses like being smelled? Thorns, maaan. Take a hint.",
    "Studying astronomy and \"taking up space\" in school two...totally different things, maaan.",
    "Sure, the stars and planets are floating in space, but what's SPACE floating in?",
    "Talented folks are just normal folks who practice something more than other folks, maaan.",
    "Talking's pretty good, as things to do with your head go, but listening is where it's at, maaan.",
    "Tall people, maaan. Is the extra reach worth all the bonked heads? The answer is up there...",
    "Teach someone to fish and they'll have fish for life. But if you give them a fish, that's just, like, easier.",
    "The ocean covers most of the earth, but that's good, because it's the best part.",
    "The ocean is salty, just like tears. Ever wonder if the earth is just crying it out?",
    "The present is the past, maaan. By the time I finish saying this sentence, it'll already be history.",
    "The sun never really sets. It just stands there doing its thing while we run circles around it.",
    "The tide covers a lot of ground, maaan, but you never see it in a hurry.",
    "There are two kinds of things: stuff that is <a native fruit>, and stuff that is not <a native fruit>, maaan.",
    "There's no rules about when pants become shorts, maaan. Call 'em what you like. Except jorts. Jorts are jorts.",
    "There's no way to describe a spider that doesn't make it sound like a bad time, maaan. Can't be done.",
    "They always reboot movies, so why not food? And can I get a sequel to carbonara? Carbonara 2, maaan!",
    "They don't make movies like they used to. They probably can't. That equipment must be busted by now.",
    "They say \"swing for the fences\" and \"go the whole nine yards,\" but, like, what if you don't play hockey?",
    "They say beauty is in the eye of the beholder, but I wonder what else might fit in there?",
    "They say dress for the job you want. Maaan, that's why I never wear a shirt.",
    "They say every writer needs an editor, but who's editing all the skywriters, maaan?",
    "They say light is the fastest thing there is, but where is it GOING, maaan?",
    "They say not to cry over spilled milk. I say go ahead. Cry over whatever you need to. Maaan, just let it out.",
    "They say not to make mountains outta molehills. But if you're making mountains, can you be that picky?",
    "They say that runners can get a second wind, but, like, what if the first one is barely even a breeze?",
    "They say that yesterday is gone, but I can still see it on my calendar, maaan.",
    "They say the apple didn't fall far from the tree, but where else was it gonna fall? Gravity calls the shots, maaan.",
    "They say the early bird gets the worm, but those evening birds seem to be doing just fine.",
    "They say to ignore your thoughts when you meditate, but after a while, it starts to feel personal, maaan.",
    "They say you can't compare apples to oranges, but that falls apart if you think about it for even one second.",
    "They say you need to get your head in the game, but seems to me that's leaving a lotta limbs on the bench...",
    "They say you should only sleep like a third of the day, but that's just a conspiracy by Big Consciousness.",
    "They won't let you test an airplane at the dealership even if you put on a tuxedo. Waste of a tux rental, maaan.",
    "They're called \"sea stars,\" but how do we know who came first? Maybe stars should be called \"sky fish.\"",
    "Think about neckties, maaan. Neck. Ties. They're tied around your neck! What's next? Torso knots?",
    "This hat's been hugging my head for a loooooong time now. In a few more years, it's gonna feel kinda awkward.",
    "Tide pools are just time-shares for tiny fish, maaan.",
    "Time is a sweetheart, always gifting you with the present. When do we give it something back, maaan?",
    "Time is nuts. Sometimes a day feels like an hour. Then you skip forward a whole day. Chaos.",
    "Trees are earth hair. And grass? A giant earth beard. Which means... deserts are the bald spots? Maaan!",
    "Wanna learn to cook? Try getting good at one recipe, then branch out. From there it's all just spices.",
    "Want to attract a bunch of otters? Scallop-shaped hot-air balloon, maaan... Otters for miles.",
    "Water bottles are too full. Chip bags are too empty. I've tried to fix this, but my chips keep getting soggy.",
    "Watermelon confuses me, maaan. Why can't we just call it fruity-foam melon? It's not foolin' anyone.",
    "We call them \"rams\" because they ram into stuff, so shouldn't otters be called \"Bob\"?",
    "We did gnats dirty. Didn't even let 'em suggest a better name. We were like, \"Gnat.\" Then they were gnats.",
    "We need a new word to describe tasty leftovers. I think we should go with \"re-licious,\" maaan...",
    "We should tell rainbows it's OK to relax. They're always so intense. We put too much pressure on 'em.",
    "We've got card sharks, pool sharks, loan sharks... Sharks need better vocational training, maaan.",
    "WHAAAAALES.",
    "What if all the planets and stars are just, like, huge atoms? And we're all just part of a giant <random object>?",
    "What if, like, ancient myths and legends were true? Archaeologists would be so confused.",
    "What the folks at the smoothie shop don't want you to know is...they're just throwin' things in a blender.",
    "What's up with crossword puzzles, maaan? Why are they so upset? Why not kindword puzzles?",
    "What's with the first eight clouds? Are they sorta good, but nothing to write home about, or what?",
    "When I swim in the sea and get wet... the ocean gets a little bit dryer. Do I, like, owe the ocean an apology?",
    "When my head gets cold, I put on my hat. My hair appreciates it. Everyone needs a little help now and then.",
    "When someone tells you to hold your horses, you tell them no. Maaan, they're way too heavy!",
    "When you can't sleep, maaan, you gotta wonder if maybe sleep just can't YOU.",
    "Where did my hat come from, maaan? Like, did I put it on once, or...was it just always there?",
    "Where do you throw a garbage can when you want to get rid of it, maaan?",
    "Wherever you are, whether you're in a house or in your own head, make it comfy. You be good to you, maaan.",
    "Whether you walk or run, you're gonna get there when you get there. That's why I backstroke, maaan.",
    "Which came first, folks named Stew, or stew? And if it was stew...what's that mean for my friend Stew's stew?",
    "Who was the first to think that eating shellfish was a good idea? Must have been an otter...",
    "Whoever decided \"humdrum\" meant \"boring\" must never have actually tried humming or drumming.",
    "Whoever named quicksand had the right idea. Regular sand is reeeeal slow, maaan.",
    "Whoever said you only sink or swim must not, like, know about pool noodles, maaan.",
    "Why are they called whiskers, maaan? Whenever I use 'em to whisk stuff, it always ends badly.",
    "Why do people say they've got an \"iron in the fire\"? Wake me when there's a marshmallow OVER the fire.",
    "Why do they call it a \"briefcase\" when that's where I keep my boxers, maaan?",
    "Why do you always see dragons sitting on piles of gold? Maaan, haven't they ever heard of banks?",
    "Why is it an insult to call someone childish? Being grown-upish is way worse. Ask any grown-up.",
    "Why is it called \"a letter\" when they always have more than one letter? Why isn't it \"some letters\"?",
    "Why is it called falling asleep? Sounds painful, maaan. Floating asleep...that's what it's all about!",
    "Why is it that fastening something means making totally sure it doesn't go fast? Words, maaan.",
    "Why'd they stop calling glasses spectacles, maaan? Guess they just couldn't live up to the hype.",
    "You always gotta go for the glory. No matter what. I mean, unless you just don't want to, maaan.",
    "You can't hug the whole world, no matter how much you want to. No one's arms are that long, maaan.",
    "You can't worry about people thinkin' you're a fake. Everything you do is real! Unless you're, like, a hologram.",
    "You do much gardening? Listen, man, forget about breeding for color. The next big thing is hybrid smells.",
    "You don't always get to do what you love, but you can always learn to love what you do.",
    "You don't have to think what others tell you to think. But if they tell you to think about popcorn, consider it.",
    "You don't know what you don't know until you do. Y'know?",
    "You don't want to miss the good ol' days too much, or you might miss out on the good new days.",
    "You ever heard of the tail wagging the dog? There's no way, maaan. I've done the math.",
    "You ever look up at the clouds in the sky and imagine shapes? They're doin' the same thing to you, maaan.",
    "You ever stop while diggin' up fossils and wonder what kinda museum you're gonna end up in someday?",
    "You ever thought about how hard it is to have an unbiased opinion about your own brain? Maaan, don't.",
    "You ever wonder when an island stops being an island and turns into just...the land? Maaaaaaan!",
    "You gotta be careful what you wish for in life. Unless you wish for ice cream. That's pretty safe.",
    "You gotta love feeling the warm sun on your back. It's like Mother Nature's putting a sweater on you.",
    "You gotta wonder why folks always ignore the elephant in the room. Elephants give the best advice, man.",
    "You know the difference between a boulder and a grain of sand? Just, like, SIZE, maaan!",
    "You know what I say? A table of contents is just an index without spoilers, maaan.",
    "You might be the star of your own life, but everybody's hosting their own reality show, maaan.",
    "You might wanna sit down for this one, maaan. A chair is just, like, a table for your butt.",
    "You wear the hat—the hat doesn't wear you. If it does, well, then you need a smaller hat, maaan.",
    "You. Me. Everyone. We've all got problems. But, man, it's comforting to know we have that in common.",
    "You? Me? Everyone on this island? We're all crossing. It's happening right...now."];

    shuffle($quotes);

?>

<html>
<head>
    <title><?php echo $quotes[0]; ?></title>
</head>
<body style="
    background-image: url(https://wallpaperaccess.com/full/115007.jpg);
    background-size: cover;
">
</body>
</html>
<h1 style="
    text-align: right;
    color: #FFFFFF;
    /* background: #FFFFFF; */
    text-shadow: 2px 2px 0 #4074b5, 2px -2px 0 #4074b5, -2px 2px 0 #4074b5, -2px -2px 0 #4074b5, 2px 0px 0 #4074b5, 0px 2px 0 #4074b5, -2px 0px 0 #4074b5, 0px -2px 0 #4074b5;
    font-family: fantasy;
    position: absolute;
    top: -45px;
    right: 30px;
    font-size: 100px;
"><?php echo $quotes[0]; ?></h1>

<img src="https://static.wikia.nocookie.net/animalcrossing/images/e/e1/Pascal_NLa.png" style="
    position: absolute;
    bottom: 30px;
    left: 30px;
"></img>
